"use strict";
exports.__esModule = true;
var LinkedList_1 = require("./LinkedList");
var genericList = new LinkedList_1.LinkedList();
genericList.add('hello');
genericList.add('test');
genericList.add('asdfasdf');
genericList.add(1);
genericList.add([1, 2]);
genericList.add('goodbye');
console.log('Generic List:', genericList.toArray());
var stringList = new LinkedList_1.LinkedList();
stringList.add('hello');
stringList.add('test');
stringList.add('asdfasdf');
stringList.add('goodbye');
console.log("String List:", stringList.toArray());
var numberList = new LinkedList_1.LinkedList();
numberList.add(1);
numberList.add(2);
numberList.add(3);
numberList.add(4);
console.log("String List:", numberList.toArray());
